### ISSUE TITLE
Topic reference autocompleted by Xcode does not resolve

### ISSUE THREAD

**Issue by stephencelis** [apple/swift-docc#330]
### Description

The following topic reference does not resolve:

https://github.com/pointfreeco/swift-composable-architecture/blob/d98e555d0e6559f1a0dc7d70603800cd33af7a03/Sources/ComposableArchitecture/Documentation.docc/Extensions/Effect.md?plain=1#L29-L30

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

I expect the topic reference to resolve.

### Actual behavior

It does not resolve. I suspect because the `Effect` type conforms to `Combine.Publisher` and has its own overload of `map`.

### Steps To Reproduce

1. Clone https://github.com/pointfreeco/swift-composable-architecture
2. Check out `d98e555d0e6559f1a0dc7d70603800cd33af7a03` (or try to use `main`)
3. Open project in Xcode 14 beta 3
4. Comment in line 30 of [`Sources/ComposableArchitecture/Documentation.docc/Extensions/Effect.md`](https://github.com/pointfreeco/swift-composable-architecture/blob/d98e555d0e6559f1a0dc7d70603800cd33af7a03/Sources/ComposableArchitecture/Documentation.docc/Extensions/Effect.md?plain=1#L30)
5. Build documentation
6. Note the warning, and observe in the documentation that the `map` method is not grouped where it should be

### Swift-DocC Version Information

Xcode 14 beta 3 (though I can reproduce in earlier versions, as well)

### Swift Compiler Version Information

```shell
swift-driver version: 1.60 Apple Swift version 5.7 (swiftlang-5.7.0.120.1 clang-1400.0.28.1)
Target: arm64-apple-macosx12.0
```

**Comment by ethan-kusters** [comment]
Hi @stephencelis! Thanks for filing this. Would you mind opening this as a Feedback instead so we can send it along to the right Xcode folks?

----

As a workaround: Swift-DocC's authored URLs are designed to match the presentation URLs used in the browser which can allow you to figure out what the correct URL is for a page even when Xcode gives the incorrect completion. 

So for the [first issue you posted](https://github.com/pointfreeco/swift-composable-architecture/blob/d98e555d0e6559f1a0dc7d70603800cd33af7a03/Sources/ComposableArchitecture/Documentation.docc/Extensions/Effect.md?plain=1#L29-L30), I ran

```
swift package --disable-sandbox preview-documentation --target ComposableArchitecture
```

navigated to: 

```
http://localhost:8000/documentation/composablearchitecture/effect
```

And scrolled down the page to find any uncurated items on the page (ones that aren't included in a Topic section). I found just the one `map` function you mentioned in an auto-generated "Instance Methods" topic group:

<img width="1097" alt="Screen Shot 2022-07-06 at 1 50 39 PM" src="https://user-images.githubusercontent.com/6750147/177641167-1dc5a24c-5fd7-4250-a228-199411911a7b.png">

If I navigate to that page I land on the following URL:

```
http://localhost:8000/documentation/composablearchitecture/effect/map(_:)-28ghh
```

which tells me that the correct authoring URL for that symbol is:

```md
``map(_:)-28ghh``
```

So if I update the [line you sent](https://github.com/pointfreeco/swift-composable-architecture/blob/d98e555d0e6559f1a0dc7d70603800cd33af7a03/Sources/ComposableArchitecture/Documentation.docc/Extensions/Effect.md?plain=1#L29-L30) to be:

```diff
### Composition

- <!--NB: DocC bug prevents the following from being resolved-->
- <!--- ``map(_:)``-->
+ - ``map(_:)-28ghh``
 - ``merge(_:)-3al9f``
 - ``merge(_:)-4n451``
 - ``concatenate(_:)-3awnj``
 - ``concatenate(_:)-8x6rz``
```

I get the desired result:


<img width="1097" alt="Screen Shot 2022-07-06 at 1 56 28 PM" src="https://user-images.githubusercontent.com/6750147/177641786-7e3f4e37-3f2a-4763-acf9-c85989d8aa33.png">

---

Obviously this would be much better if Xcode code completion gave the correct result originally though- so a Feedback would be really appreciated so the right folks can figure out what's going on here.

@d-ronnqvist is also actively looking into improving DocC's link-resolution infrastructure to support producing diagnostics for cases like that to offer better Fix-Its when a link is _close_ but not quite correct.

---

I'm going to close this out since it's not something we can resolve in the open source repo but thank you for filing this!

**Comment by stephencelis** [comment]
@ethan-kusters Is there a Swift bot out there yet that can automate opening this feedback?

**Comment by stephencelis** [comment]
(Also, thanks for the workaround!)

**Comment by ethan-kusters** [comment]
> @ethan-kusters Is there a Swift bot out there yet that can automate opening this feedback?

Unfortunately there's not 😬 

> (Also, thanks for the workaround!)

No problem!

**Comment by stephencelis** [comment]
@ethan-kusters Filed FB10569833 for the issue above if you want to track it.

Also filed FB10569922, "Impossible to know what DocC will autocomplete for many overloads". Since Xcode 13, I believe, Xcode autocomplete was restyled and a lot of type information is now omitted. This type information can be critical to distinguish some overloads. Hopefully your workaround will help us in the meantime here, as well.

**Comment by ethan-kusters** [comment]
@stephencelis thank you so much! I really appreciate it.
