### ISSUE TITLE
Add  `deprecated` version argument to the `@Available` directive

### ISSUE THREAD

**Issue by QuietMisdreavus** [apple/swift-docc#441]
### Feature Name

Specify deprecated version in `@Available` directive

### Description

The initial implementation of `@Available` (https://github.com/apple/swift-docc/pull/440) only supports specifying the "introduced" version. We should add support for specifying a "deprecated" version as well.

**Comment by d-ronnqvist** [comment]
I would argue that we shouldn't add `isBeta` and `isDeprecated` arguments _specifically_ because it makes `@Available` work completely different than in-source availability. 

- `isBeta` is an attribute of the current platform, which is provided via a command line argument
- `isDeprecated` is a an attribute that's based on the version that the page is deprecated in. Instead we could add a `deprecated` version argument to match the `introduced` argument.

**Comment by d-ronnqvist** [comment]
Adding a new argument to an existing directive is a pretty good first task for someone who wants to learn about how directives work in DocC. There are existing tests for this type that can be updated to cover combinations of both arguments.

**Comment by mustiikhalil** [comment]
Hey, I am wondering if this is still open! I would love to pick it up and add the new directive into DocC.

**Comment by d-ronnqvist** [comment]
@mustiikhalil yes, AFAIK this is still open and no-one has started working on it yet. That said, might be worth double checking with @sofiaromorales who is working on some other availability improvements.

**Comment by mustiikhalil** [comment]
That's perfect, I can pick it up after input from @sofiaromorales incase it's still needed.

**Comment by sofiaromorales** [comment]
@mustiikhalil, sure, feel free to take on this issue 🙂

**Comment by mustiikhalil** [comment]
So I started working on it here #851 and from what I can see, I've implemented all the required fields for it to work as expected, however I wonder if I missed something.
