### ISSUE TITLE
`convert` and `preview` commands crash on certain Markdown pages

### ISSUE THREAD

**Issue by MaxDesiatov** [apple/swift-docc#678]
### Description

When rendering Swift compiler documentation the diagnostics formatting code crashes on certain Markdown pages.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

No crashes.

### Actual behavior

`Swift/StringCharacterView.swift:158: Fatal error: String index is out of bounds`

### Steps To Reproduce

1. Clone https://github.com/apple/swift.git
2. Install a recent development snapshot of Swift, I'm using `swift-DEVELOPMENT-SNAPSHOT-2023-07-23-a`.
3. Run DocC from this snapshot this way (assuming `swift` is the clone from step 1):
```
docc preview --allow-arbitrary-catalog-directories swift/docs
```

### Swift-DocC Version Information

swift-DEVELOPMENT-SNAPSHOT-2023-07-23-a

### Swift Compiler Version Information

```shell
Apple Swift version 5.9-dev (LLVM 9b562f55c38e378, Swift b4ee68bd37c4f7d)
Target: arm64-apple-macosx14.0
```

**Comment by arthurcro** [comment]
> The code that crashes is in the new diagnostics formatter (#535). cc @arthurcro if you have any ideas 🙂

Thank you for the heads up, I’ll take a look asap! 🙂

**Comment by MaxDesiatov** [comment]
@arthurcro this is still reproducible on `main` with f70b3ea, I'm reopening the issue
<img width="1093" alt="Screenshot 2023-08-11 at 11 54 29" src="https://github.com/apple/swift-docc/assets/112310/b9d31219-3136-4f10-9a00-986d466c57d4">

**Comment by arthurcro** [comment]
> @arthurcro this is still reproducible on `main` with [f70b3ea](https://github.com/apple/swift-docc/commit/f70b3ea281773121a468d9c0966ab8a34bba58d2), I'm reopening the issue

Thank you for reopening the issue and apologies for the inconvenience.
The crash is surprising, I did not face any crashes when I tested it after implementing the fix. Did you change anything this time compared to the steps mentioned in the _Steps to reproduce_ ?

**Comment by MaxDesiatov** [comment]
I didn't, potentially more docs were published in the `docs` directory in question. But this crash looked similar if it wasn't the same as the original issue, so I felt that reopening this one would work better than creating a new one.

**Comment by arthurcro** [comment]
Hi! 😄 I'm unfortunately unable to reproduce the issue on `main` with the latest `docs` from https://github.com/apple/swift. 
@franklinsch @d-ronnqvist could you check if you can reporduce if you have some time? 😊

**Comment by MaxDesiatov** [comment]
Reproduced again with `main` DocC, checkout this commit with the docs: https://github.com/apple/swift/commit/1de261bb28b99c6d63a325fef84c854415ab7a32

**Comment by arthurcro** [comment]
Great! I can reproduce with this commit, thank you! 🙇🏻

**Comment by arthurcro** [comment]
Hi! :wave: After some investigation, I've identified what seems to be the underlying cause of the problem.

Interestingly, the issue doesn't seem to be directly caused by the improved default diagnostic formatter, even though the formatter does highlight it.

While I might not have captured all the details accurately, here's my understanding so far:

When using:

```
`` my content ``
```

DocC will see this as a symbol link.

For this specific crash, when using:

```
  for the target platform and verify diagnostics, like ``swift -frontend -typecheck -verify
%s``
```

DocC will try to resolve this symbol link as a `TopicReference` but it will eventually fail. 

https://github.com/apple/swift-docc/blob/f70b3ea281773121a468d9c0966ab8a34bba58d2/Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift#L161

To resolve the symbol link and eventually emit a diagnostic for this resolution error, DocC uses the symbol link `SourceRange` provided by [MarkupData.swift](https://github.com/apple/swift-markdown/blob/3d4b36cff09f785adf5efb190d458a3d44e6df87/Sources/Markdown/Base/MarkupData.swift#L137-L140) from `swift-markdown`.

This source range is used as the diagnostic's source range in case of resolution error. It's then used by the default diagnostic formatter to highlight the unresolved reference. If the source range does not match the actual content of the source file, it crashes. 

If we look at your crash, we get a `SourceRange` `253:56-253:97` while if we look at the source file content, we should be getting `253:56-254:5`.  It seems we are getting an incorrect source range for some symbol links. 

I hope that made sense.
@d-ronnqvist I'm not sure how to proceed to fix this issue. Could you advice possible next steps? 🙇🏻

**Comment by Kyle-Ye** [comment]
Thanks for pointing it out. Maybe you can help file up a issue with some minimum reproducible input to Swift-Markdown so that I can help to look at it on the Markdown module side. (QuietMisdreavus should have some better insights on such problem. But it looks like she is busy now and will back September 18)

Also to know that there are several other issues about SourceRange parsing like https://github.com/apple/swift-markdown/issues/71. I have tried to fix it, but the CodeReview process is pending for some unknown reason.

**Comment by Kyle-Ye** [comment]
I'm also frequently encountered this locally. This should definitely be a block issue for release/5.10 since it may crash a lot of downstream user.

Maybe we can discuss it in next DocC workgroup. cc @franklinsch @QuietMisdreavus 

IMO, We should either fix it before 5.10 release or revert relevant PR until we fix the issue.

**Comment by Kyle-Ye** [comment]
> I hope that made sense. @d-ronnqvist I'm not sure how to proceed to fix this issue. Could you advice possible next steps? 🙇🏻

For the problem you found, I've open a PR to fix it. https://github.com/apple/swift-markdown/pull/151 cc @arthurcro 

And there is another crash cause, I've opened a new issue on swift-docc to track it. #729

**Comment by Kyle-Ye** [comment]
Both bugfix PR is merged into main. The cherry-pick to release/5.10 is still in progress.
- https://github.com/apple/swift-docc/pull/746
- https://github.com/apple/swift-markdown/pull/156

If you are still encountering such crash on the toolchain, feel free to reopen the issue. @MaxDesiatov
