### ISSUE TITLE
Support svg images in Xcode inline documentation

### ISSUE THREAD

**Issue by Vaida12345** [apple/swift-docc#794]
### Feature Name

Support svg images in Xcode inline documentation

### Description

Hi,
It would be great if you can support svg images in Xcode inline documentation. I know this could be the wrong place to ask. Or, can you support pdf docs in DocC please?

### Motivation

Sometimes, one wishes to use images to aid the explanation of functions or structures. I know I can achieve this using `png`s, but vector images can deliver higher (infinite) resolution with smaller file size. Furthermore, `svg`s are easier to edit, enabling the use of commands to generate dark style images. Such as 
```shell
sed -e 's/rgb(0%, 0%, 0%)/#FFFFFF/g' -e 's/#000000/#FFFFFF/g' "$modified_path" > "$modified_path_dark"
```

### Importance

This can currently be achieved by using `png`s. However, as mentioned above, using `svg`s would definitely improve the user experience.

### Alternatives Considered

We can also use `pdf`s, however, currently DocC generated documentations cannot show `pdf` documents.

**Comment by Kyle-Ye** [comment]
1. For Xcode feature request, please go for Apple's Feedback system
2. That's it, but as far as I know, most of the functions supported by swift-docc are generally supported by Xcode. In general, Xcode might expand the function set of swift-docc, and I haven't seen it deleted some feature set for the time being.
3. So I assume you are asking for svg image support in swift-docc. And we should have supported this in #4.

[Uploading 794.zip…]()

SVG are supported  on in-source doc and article file. I've Tested it under Xcode 15.0 and the latest version of swift-docc-render. 

If you still have issue with svg, feel free to ask and reopen the issue.

**Comment by Kyle-Ye** [comment]
I might know you issue now.

The Xcode Documentation Preview does not support svg for some unknown reason. (The final product is fine when you browse the doc via Xcode documentation or swift-docc-render)

As far as I know @franklinsch is in charge of this. You should file a FB so that their team can track it in Apple internally.

Anyway this issue is out of scope of swift-docc open source project.

New Demo Package to reproduce ⬇️: 
[794.zip](https://github.com/apple/swift-docc/files/13898371/794.zip)

<img width="1459" alt="image" src="https://github.com/apple/swift-docc/assets/43724855/524507ca-035f-4695-aba4-cacce3e9b9bd">

<img width="1420" alt="image" src="https://github.com/apple/swift-docc/assets/43724855/0d619408-c6ef-4d99-baf6-465b65078f3d">
